# Generated by Django 3.1.2 on 2020-10-05 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addproductmodel',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='addproductmodel',
            name='product_added_by',
        ),
        migrations.RemoveField(
            model_name='addproductmodel',
            name='updated_at',
        ),
    ]
