# Generated by Django 3.1.2 on 2020-10-07 06:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20201005_1146'),
    ]

    operations = [
        migrations.AddField(
            model_name='addproductmodel',
            name='price',
            field=models.CharField(default=django.utils.timezone.now, max_length=150),
            preserve_default=False,
        ),
    ]
