# Generated by Django 3.1.2 on 2020-10-08 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_clientlogin'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartCreator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=150)),
                ('client_id', models.CharField(max_length=150)),
                ('total_price', models.CharField(max_length=150)),
                ('product_count', models.CharField(max_length=20)),
            ],
        ),
    ]
